/* eslint-disable no-unused-vars */
/**
 * 基础屏幕尺寸
 * 以iPhone6为基准
 */
enum BASE_SCREEN_SIZE {
    BASE_WIN_WIDTH = 375,
    BASE_WIN_HEIGHT = 667
}

/**
 * 字符串常量
 */
enum CONSTS_VALUE {
    SCREEN_HEIGHT = 'SCREEN_HEIGHT',
    SCREEN_WIDTH = 'SCREEN_WIDTH',
    STATUSBAR_HEIGHT = 'STATUSBAR_HEIGHT',
    BOTTOMTABS_HEIGHT = 'BOTTOMTABS_HEIGHT',
    LOGIN_STATUS = 'LOGIN_STATUS',
}

/**
 * 样式类常量
*/
enum CONSTS_STYLE_VALUE {
    PAGE_BG_COLOR = '#F6F6F6',
    BOTTOMBAR_COLOR = '#FFFFFF'
}

export { BASE_SCREEN_SIZE, CONSTS_VALUE, CONSTS_STYLE_VALUE };